'use client'

import { useState } from 'react'
import { ArrowRight, Check, Droplets, Instagram, Mail, Menu, Phone, QrCode, Ticket, Users, X } from 'lucide-react'

const reasons=[['100% Hand-to-Hand Distribution','Every box reaches an engaged attendee who will use it.'],['No Wasted Impressions','Unlike flyers or banners, every unit drives measurable action.'],['High-Value Active Audience','Target participants who are already engaged and motivated.'],['Offers That Get Redeemed','Detachable vouchers drive actual store visits and conversions.'],['Utility That Drives Brand Recall',"People don't throw it away. They use it."]]
const environments=[['Corporate Events','Conferences and business gatherings.'],['Universities','Campus events and student activities.'],['Festivals','Cultural and music celebrations.'],['Tournaments','Sports competitions and championships.'],['Exhibitions','Trade shows and industry events.']]
const Logo=({footer=false})=><a className={`officialLogo ${footer?'footerLogo':''}`} href="#top"><img src="/images/cool-boxpng.png" alt="Cool Box — Stay cool. Save more"/></a>

export default function Home(){const[menuOpen,setMenuOpen]=useState(false);const closeMenu=()=>setMenuOpen(false);return <main>
<header className="nav shell"><Logo/><nav><a href="#what">What is Cool Box?</a><a href="#why">Why Cool Box?</a><a href="#environments">Where It Works</a><a href="#offer">Advertising Offer</a></nav><a className="button desktopCta" href="#contact">Advertise with us</a><button className="menuButton" aria-label={menuOpen?'Close menu':'Open menu'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button>{menuOpen&&<div className="mobileMenu"><a onClick={closeMenu} href="#what">What is Cool Box?</a><a onClick={closeMenu} href="#why">Why Cool Box?</a><a onClick={closeMenu} href="#environments">Where It Works</a><a onClick={closeMenu} href="#offer">Advertising Offer</a><a onClick={closeMenu} className="button" href="#contact">Advertise with us</a></div>}</header>
<section className="hero" id="top"><div className="heroGlow glowOne"></div><div className="heroGlow glowTwo"></div><div className="shell heroGrid"><div className="heroText"><p className="kicker">AN INNOVATIVE MARKETING & ENGAGEMENT CONCEPT</p><h1>Smart advertising<br/>that <em>moves with<br/>your audience.</em></h1><p className="lead">Cool Box delivers a fresh approach to connecting with consumers — combining hydration, redeemable offers and smart advertising in one physical experience.</p><div className="heroActions"><a className="button" href="#what">Discover Cool Box <ArrowRight size={17}/></a><a className="plain" href="#offer">View advertising offer</a></div></div><div className="heroComposition"><div className="visualHalo"></div><div className="heroRing ringA"></div><div className="heroRing ringB"></div><img className="heroWater waterBack" src="/images/droplets.png" alt=""/><img className="heroIce iceBack" src="/images/ice-cubes.png" alt=""/><img className="heroProduct" src="/images/box-bottle.png" alt="Cool Box with chilled water bottle"/><img className="heroCoupon couponOne" src="/images/coupon-1.png" alt=""/><img className="heroCoupon couponTwo" src="/images/coupon-2.png" alt=""/><img className="heroCoupon couponThree" src="/images/coupon-3.png" alt=""/><img className="heroCoupon couponFour" src="/images/coupon-4.png" alt=""/><img className="heroIce iceFront" src="/images/ice-cubes.png" alt=""/><span className="bubble bubble1"></span><span className="bubble bubble2"></span><span className="bubble bubble3"></span></div></div><div className="shell heroValueStrip"><div><span>01</span><b>HYDRATION</b><small>Essential water for active participants</small></div><div><span>02</span><b>SAVINGS</b><small>8 redeemable offers from multiple brands</small></div><div><span>03</span><b>SMART ADVERTISING</b><small>Measurable engagement and real results</small></div></div></section>
<section className="what" id="what"><div className="shell"><div className="sectionTitle"><span></span><div><p>WHAT IS THE “COOL BOX”?</p><h2>Hydration + <em>8 redeemable offers.</em></h2></div></div><div className="whatGrid"><div className="conceptCard"><div className="conceptVisual"><div className="conceptGlow"></div><img className="conceptWater" src="/images/droplets.png" alt=""/><img className="conceptIce" src="/images/ice-cubes.png" alt=""/><img className="conceptBox" src="/images/box-2.png" alt="Cool Box advertising panels"/><img className="conceptCoupon conceptCouponA" src="/images/coupon-3.png" alt="Example removable Cool Box voucher"/><img className="conceptCoupon conceptCouponB" src="/images/coupon-1.png" alt=""/><img className="conceptCoupon conceptCouponC" src="/images/coupon-4.png" alt=""/></div></div><div className="facts"><div><Droplets/><p><b>Chilled water bottles</b> are placed inside the Cool Box and distributed <b>FREE to the audience.</b></p></div><div><Ticket/><p>The exterior features <b>8 separate ad panels</b>. Each ad is designed as a <b>removable voucher coupon.</b></p></div><div><Check/><p>Consumers can tear off coupons and redeem them for <b>discounts, freebies or offers</b> at the advertiser’s business.</p></div><div><Users/><p>Cool Box delivers <b>brand exposure + direct customer engagement</b> at the same time.</p></div></div></div></div></section>
<section className="why" id="why"><div className="shell"><div className="sectionTitle white"><span></span><div><p>WHY COOL BOX?</p><h2>Zero waste.<br/><em>Maximum impact.</em></h2></div></div><div className="reasonGrid">{reasons.map((r,i)=><article key={r[0]}><strong>0{i+1}</strong><h3>{r[0]}</h3><p>{r[1]}</p></article>)}</div></div></section>
<section className="ctaFlow"><div className="shell"><div className="sectionTitle"><span></span><div><p>FROM EXPOSURE TO ACTION</p><h2>Awareness → Interaction → <em>Store Visit</em></h2></div></div><div className="flow"><div><QrCode/><h3>Sponsors Place Offers</h3><p>Brands add redeemable vouchers to the Cool Box.</p></div><i></i><div><Ticket/><h3>Box to Attendees</h3><p>Handed directly to engaged participants at events and active environments.</p></div><i></i><div><Users/><h3>Brands Track Engagement</h3><p>Real data on redemptions and store visits.</p></div></div></div></section>
<section className="audience" id="environments"><div className="shell"><div className="sectionTitle"><span></span><div><p>BUILT FOR ACTIVE ENVIRONMENTS</p><h2>Advertising people<br/><em>actually use.</em></h2></div></div><p className="sectionIntro">A branded hydration box designed for real engagement — from sports courts to large-scale events.</p><div className="environmentGrid">{environments.map((item,i)=><article key={item[0]}><span>0{i+1}</span><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div><p className="anywhere">Anywhere People Gather. Anywhere Brands Want Presence.</p></div></section>
<section className="network"><div className="shell networkGrid"><div><p className="kicker pale">WE STARTED WHERE ENERGY IS HIGH</p><h2>Built to engage<br/><em>active communities.</em></h2><p className="networkIntro">Cool Box began in environments where hydration is essential and engagement is natural. The concept is designed to scale wherever people gather and brands want meaningful presence.</p><div className="startGrid"><div><strong>Padel Courts</strong><span>Where hydration is essential and engagement is natural.</span></div><div><strong>Sports Complexes</strong><span>Active communities seeking quality experiences.</span></div><div><strong>Active Communities</strong><span>Engaged participants ready to redeem offers.</span></div></div></div><figure className="padelMoment"><img src="/images/box-padel.png" alt="Cool Box displayed beside a padel court"/><figcaption><span>IN THE REAL WORLD</span><strong>Right where the audience is.</strong></figcaption></figure></div></section>
<section className="offer" id="offer"><div className="shell"><div className="sectionTitle"><span></span><div><p>ADVERTISING OFFER</p><h2>Your space on<br/><em>Cool Box.</em></h2></div></div><div className="offerGrid"><div className="price"><small>AD SPACE</small><strong>6 × 10 cm</strong><p>Dedicated removable voucher panel</p></div><div className="offerDetails"><div><strong>4,000</strong><span>boxes distributed per campaign</span></div><div><strong>8</strong><span>coupon ads per box</span></div><div><strong>4</strong><span>faces available for strip ad banners</span></div><div><strong>2</strong><span>strip banners — top & bottom</span></div></div><p className="ideal"><b>Ideal for:</b> restaurants, cafés, sports stores and lifestyle venues aiming to boost visits.</p></div></div></section>
<section className="contact" id="contact"><div className="shell"><p>BRING COOL BOX TO YOUR NEXT EVENT</p><h2>Hydration. Savings.<br/><em>Smart advertising.</em></h2><p className="contactLead">Essential water, 8 redeemable offers from multiple brands, measurable engagement and real results.</p><div className="contactActions"><a className="contactMethod" href="tel:009613152071"><span className="contactIcon"><Phone size={19}/></span><span><strong>+961 3 152 071</strong></span></a><div className="contactMethod"><a className="contactIcon" href="mailto:wael@sparxme.com" aria-label="Email Cool Box"><Mail size={19}/></a><span><strong>wael@sparxme.com</strong></span></div></div><div className="socialFollow"><span>FOLLOW US</span><a href="https://www.instagram.com/cool_box.official/" target="_blank" rel="noreferrer" aria-label="Follow Cool Box on Instagram"><Instagram size={22}/></a></div><div className="sparx"><img src="/images/sparx-logo.png" alt="SPARX Media Solutions"/></div></div></section>
<footer><div className="shell"><Logo footer/><p>© {new Date().getFullYear()} Cool Box · SPARX Media Solutions</p></div></footer>
</main>}
