'use client'

import { ArrowRight, Check, Droplets, MapPin, QrCode, Ticket, Users } from 'lucide-react'

const reasons = [
  ['Hyper-Targeted','Reach padel players directly — no wasted impressions.'],
  ['Physical Touchpoint','Your ad is held, seen and remembered, unlike digital ads.'],
  ['Ads Stand Out','Only 8 ads on the box — no ad clutter.'],
  ['High Engagement','Connect with your audience, build awareness and convert to sales.'],
  ['Premium Venues','Distributed at leading padel clubs and sports centers.'],
]
const venues = ['The Padelist — Achrafieh Courts','The Padelist — Ein El Remmane','The Padelist — Zalka Courts','The Padelist — Dbayeh / Naccache Courts','The Racket Concept — Furn El Chebbek']
const Logo=({footer=false})=><a className={`officialLogo ${footer?'footerLogo':''}`} href="#top"><img src="/images/cool-boxpng.png" alt="Cool Box — Stay cool. Save more"/></a>

export default function Home(){return <main>
<header className="nav shell"><Logo/><nav><a href="#what">What is Cool Box?</a><a href="#why">Why Cool Box?</a><a href="#network">Our Network</a><a href="#offer">Advertising Offer</a></nav><a className="button" href="#contact">Advertise with us</a></header>
<section className="hero" id="top"><div className="shell heroGrid"><div className="heroText"><p className="kicker">AN INNOVATIVE ADVERTISING & ENGAGEMENT CONCEPT</p><h1>Connect with<br/><em>padel players</em><br/>at the peak<br/>of their game.</h1><p className="lead">Cool Box delivers a fresh approach to connecting with consumers through branded water bottle boxes, removable voucher coupons and direct calls to action.</p><div className="heroActions"><a className="button" href="#what">Discover Cool Box <ArrowRight size={17}/></a><a className="plain" href="#offer">View advertising offer</a></div></div><div className="productStage"><div className="box"><div className="boxTop">COOL BOX</div><div className="boxFace"><img className="boxLogo" src="/images/cool-boxpng.png" alt=""/><div className="ad a1">YOUR<br/>BRAND</div><div className="ad a2">20%<br/><small>OFF</small></div><div className="ad a3">SCAN<br/><QrCode size={26}/></div><div className="ad a4">TRY<br/>ME</div></div></div><div className="bottle"></div><span className="voucher v1">10% OFF</span><span className="voucher v2">FREEBIE</span><span className="voucher v3">SCAN ME</span></div></div></section>
<section className="what" id="what"><div className="shell"><div className="sectionTitle"><span></span><div><p>WHAT IS THE “COOL BOX”?</p><h2>A box built to deliver<br/><em>exposure + engagement.</em></h2></div></div><div className="whatGrid"><div className="courtScene"><div className="courtLines"></div><div className="courtBox"><img src="/images/cool-boxpng.png" alt="Cool Box"/></div><span>PADEL COURT</span></div><div className="facts"><div><Droplets/><p><b>Chilled water bottles</b> are placed inside the Cool Box and distributed <b>FREE</b> to padel players.</p></div><div><Ticket/><p>The exterior features <b>8 separate ad panels</b>, each designed as a removable voucher coupon.</p></div><div><Check/><p>Consumers can tear off coupons and redeem them for <b>discounts, freebies or offers</b> at the advertiser’s business.</p></div><div><Users/><p>Brand exposure and <b>direct customer engagement</b> happen at the same time.</p></div></div></div></div></section>
<section className="why" id="why"><div className="shell"><div className="sectionTitle white"><span></span><div><p>WHY ADVERTISE ON COOL BOX?</p><h2>Physical. Focused.<br/><em>Actionable.</em></h2></div></div><div className="reasonGrid">{reasons.map((r,i)=><article key={r[0]}><strong>0{i+1}</strong><h3>{r[0]}</h3><p>{r[1]}</p></article>)}</div></div></section>
<section className="ctaFlow"><div className="shell"><div className="sectionTitle"><span></span><div><p>UNIQUE CALL TO ACTION</p><h2>Coupon redemption that<br/><em>drives real visits.</em></h2></div></div><div className="flow"><div><QrCode/><h3>Include a QR Code</h3><p>Show your menu or social media page on your ad face and grow interaction organically.</p></div><i></i><div><Ticket/><h3>Example Offers</h3><p>Turn exposure into a clear incentive with discounts, freebies and redeemable offers.</p></div><i></i><div><Users/><h3>Redemption Tracking</h3><p>Measure campaign effectiveness through unique usage.</p></div></div></div></section>
<section className="audience"><div className="shell"><div className="sectionTitle"><span></span><div><p>TARGET AUDIENCE</p><h2>Premium, active<br/>and <em>social.</em></h2></div></div><div className="audGrid"><article><span>01</span><h3>Padel Players & Sports Enthusiasts</h3><p>Active individuals passionate about sports and fitness.</p></article><article><span>02</span><h3>Young Professionals & Active Adults</h3><p>Individuals with disposable income and a desire for premium experiences.</p></article><article><span>03</span><h3>Trend-Conscious Consumers</h3><p>Consumers focused on wellness and modern lifestyles.</p></article></div></div></section>
<section className="network" id="network"><div className="shell networkGrid"><div><p className="kicker pale">OUR NETWORK — GREATER BEIRUT</p><h2>Direct access to<br/><em>padel players.</em></h2><p className="networkIntro">Branded water bottle boxes are distributed free with court reservations, building a direct and personal connection with active customers.</p><div className="venueList">{venues.map(v=><div key={v}><MapPin size={17}/><span>{v}</span></div>)}</div></div><div className="mapPanel"><div className="coast"></div><i className="pin p1"></i><i className="pin p2"></i><i className="pin p3"></i><i className="pin p4"></i><i className="pin p5"></i><span>GREATER<br/>BEIRUT</span></div></div></section>
<section className="offer" id="offer"><div className="shell"><div className="sectionTitle"><span></span><div><p>ADVERTISING OFFER</p><h2>Your space on<br/><em>Cool Box.</em></h2></div></div><div className="offerGrid"><div className="price"><small>PRICE PER AD SPACE</small><strong>$600</strong><p>Ad size: 6(w) × 10(h) cm</p></div><div className="offerDetails"><div><strong>4,000</strong><span>boxes distributed per campaign</span></div><div><strong>8</strong><span>coupon ads per box</span></div><div><strong>$300</strong><span>strip ad banner on 4 faces</span></div><div><strong>2</strong><span>strip banners — top & bottom</span></div></div><p className="ideal"><b>Ideal for:</b> restaurants, cafés, sports stores and lifestyle venues aiming to boost visits.</p></div></div></section>
<section className="contact" id="contact"><div className="shell"><p>CALL TO ACTION</p><h2>Turn padel players into<br/><em>your loyal customers.</em></h2><p className="contactLead">Connect with padel players and boost your business.</p><a className="button light" href="tel:03152071">Contact us — 03 152 071 <ArrowRight size={17}/></a><div className="sparx">SPAR<span>X</span><small>MEDIA SOLUTIONS</small></div></div></section>
<footer><div className="shell"><Logo footer/><p>© {new Date().getFullYear()} Cool Box · SPARX Media Solutions</p></div></footer>
</main>}
